name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/adenblack_django@master
    - name: Run a multi-lines script
      run: |
        pwd
        echo pwd > test.txt
